safe:        false
port: 4000
baseurl:     /
url:         https://norfolkjs.com
source:      .
destination: ./_site
# plugins:     ./plugins_dir
future:      true
markdown:    kramdown
permalink:   date
